name: Build and Deploy

on:
  push:
    branches:
      - localMaster

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        npm install --save-dev webpack webpack-cli
        npm install @emotion/core @emotion/styled

    - name: Build
      run: |
        npm ci
        cp ./404.html ./public/404.html
        npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.HOMEPAGE_TOKEN }}
        publish_dir: ./build